---
  - name: Install Mysql-Server and zabbix-server
    yum: name={{ item }} state=latest
    with_items:
         - mysql-server
         - zabbix-server
         - zabbix-server-mysql 
         - zabbix-web-mysql
  - name: Init Mysql
    shell: mysql_install_db
  - name: Start mysql-server
    service: name=mysqld state=started enabled=yes
  - name: Set mysql admin password
    shell: /usr/bin/mysqladmin -u root  password 'ansible'
  - name: Create Zabbix master databases
    shell: mysql -u root -pansible -e 'create database zabbix_master character set utf8 collate utf8_bin;'
  - name: Set Zabbix Master databases grant
    shell: mysql -u root -pansible -e 'grant all privileges on zabbix_master.* to zabbix@localhost identified by "master";'
  - name: Import zabbix initial data (schema.sql)
    shell: mysql -u zabbix -pmaster zabbix_master < schema.sql  chdir=/usr/share/doc/zabbix-server-mysql-2.4.6/create 
  - name: Import zabbix initial data (images.sql)
    shell: mysql -u zabbix -pmaster zabbix_master < images.sql  chdir=/usr/share/doc/zabbix-server-mysql-2.4.6/create 
  - name: Import zabbix initial data (data.sql)
    shell: mysql -u zabbix -pmaster zabbix_master < data.sql  chdir=/usr/share/doc/zabbix-server-mysql-2.4.6/create 
  - name: Copy /etc/zabbix/zabbix_server.conf files
    template: src=zabbix_server.conf dest=/etc/zabbix/zabbix_server.conf owner=root group=root mode=644
  - name: change PHP timezone
    shell: sed -e 's@;date.timezone =.*@date.timezone = Asia/Shanghai@g' /etc/php.ini
  - name: Start Zabbix-Server and httpd 
    service: name={{ item }} state=started enabled=yes
    with_items:
       - zabbix-server
       - httpd
