---
  - name: Install Mysql-Server and zabbix-server
    yum: name={{ item }} state=latest
    with_items:
         - mysql-server
         - zabbix-proxy
         - zabbix-proxy-mysql 
  - name: Init Mysql
    shell: mysql_install_db
  - name: Start mysql-server
    service: name=mysqld state=started enabled=yes
  - name: Set mysql admin password
    shell: /usr/bin/mysqladmin -u root  password 'ansible'
  - name: Create Zabbix master databases
    shell: mysql -u root -pansible -e 'create database zabbix_proxy character set utf8 collate utf8_bin;'
  - name: Set Zabbix Master databases grant
    shell: mysql -u root -pansible -e 'grant all privileges on zabbix_proxy.* to zabbix@localhost identified by "proxy";'
  - name: Import zabbix initial data (schema.sql)
    shell: mysql -u zabbix -pproxy zabbix_proxy < schema.sql  chdir=/usr/share/doc/zabbix-proxy-mysql-2.4.6/create/
  - name: Copy /etc/zabbix/zabbix_proxy.conf files
    template: src=zabbix_proxy.conf dest=/etc/zabbix/zabbix_proxy.conf owner=root group=root mode=644
  - name: Start Zabbix-Server and httpd 
    service: name=zabbix-proxy state=started enabled=yes

